# Generated by Django 5.1 on 2024-08-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('cinema_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.PositiveIntegerField(default=0)),
                ('schedule', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_scheduled_movies', to='cinema.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_movies', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_identifier', models.CharField(default='', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tickets', to='accounts.profile')),
                ('scheduled_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_tickets', to='cinema.scheduledmovie')),
            ],
        ),
    ]
